# SITE SETTINGS
title: GeoLocator DP
author: GeoLocator Development Team
url: https://raphaelnussbaumer.com
baseurl: /GeoLocator-DP

# SOCIAL PROFILES
social:
  github: rafnuss/geolocator-dp

# THEME SETTINGS
theme: minima
remote_theme: tdwg/petridish
# github_edit: true
logo: /assets/logo.png
colors:
  links: "#007bff" # Color for links: use a readable color that contrasts well with dark text
  banner: "#516f6a" # Background color for page banners: use color that contrasts well with white
  footer: "#516f6a" # Background color for footer: use color that contrasts well with white
font_serif: true # Font type for page content: serif (default) or slightly smaller sans-serif
rounded_corners: true # Enable (default) rounded corners on boxes and buttons

# BUILD SETTINGS
# The repository contains symlinks and therefore requires GitHub Actions to build the website
# See https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/troubleshooting-jekyll-build-errors-for-github-pages-sites#config-file-error
repository: rafnuss/GeoLocator-DP # Required so Jekyll on GitHub Actions can access repo metadata
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - tests/*
  - "*.json"
  - vendor # Avoids https://github.com/jekyll/jekyll/issues/2938

