name: Validate profile and schemas

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-profile-and-schemas:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install -r tests/requirements.txt --upgrade pip
    - name: Run validation tests
      run: |
        python tests/validate_profile_and_schemas.py
